apiVersion: v1
kind: Service
metadata:
  name: addressbook
spec:
  type: NodePort
  selector:
    app: addressbook
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 30002

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: addressbook-deployment
  labels:
    app: addressbook
spec:
  replicas: 6
  selector:
    matchLabels:
      app: addressbook
  template:
    metadata:
      labels:
        app: addressbook
    spec:
      containers:
      - name: addressbook
        image: sriram226/ci-cd:tagVersion
        ports:
        - containerPort: 8080
